"use strict";

var Event = require('./Event');

module.exports = {
  AnimationEvent: Event,
  AudioProcessingEvent: Event,
  BeforeUnloadEvent: Event,
  CallEvent: Event,
  ClipboardEvent: Event,
  CompositionEvent: Event,
  CustomEvent: require('./CustomEvent'),
  DeviceLightEvent: Event,
  DeviceMotionEvent: Event,
  DeviceOrientationEvent: Event,
  DeviceProximityEvent: Event,
  DeviceStorageChangeEvent: Event,
  DragEvent: Event,
  Event: Event,
  ExtendableMessageEvent: Event,
  FocusEvent: Event,
  GamepadEvent: Event,
  KeyboardEvent: Event,
  MessageEvent: Event,
  MouseEvent: require('./MouseEvent'),
  MutationEvent: Event,
  MutationNameEvent: Event,
  NotificationEvent: Event,
  OfflineAudioCompletionEvent: Event,
  PageTransitionEvent: Event,
  PointerEvent: Event,
  PopStateEvent: Event,
  PopupEvent: Event,
  ProgressEvent: Event,
  PushEvent: Event,
  SMSEvent: Event,
  SVGEvent: Event,
  SVGZoomEvent: Event,
  ServiceWorkerMessageEvent: Event,
  SpeechSynthesisEvent: Event,
  StorageEvent: Event,
  TimeEvent: Event,
  TouchEvent: Event,
  TransitionEvent: Event,
  UIEvent: require('./UIEvent'),
  UserProximityEvent: Event,
  WheelEvent: Event
};
